upstream ticketmaster_backend {

    server backend-service:8080;
}

# 2. Configuramos el servidor Nginx
server {
    listen 80;
    server_name localhost;

    location / {
        # Apuntamos todo el tráfico al cluster que creamos arriba
        proxy_pass http://ticketmaster_backend;

        # Pasamos la información original del usuario a tu Java
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}